FROM python:3.11-slim


WORKDIR /app

COPY requirements.txt .
COPY app.py .
COPY templates templates/
COPY static static/

RUN pip3 install --no-cache-dir -r requirements.txt
# ENV REDIS_HOST=${REDIS_HOST}

EXPOSE 5000

CMD [ "flask", "run", "--host=0.0.0.0"]