apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-conf
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / { return 200 "Olaaaaa BIPEDESSS!"; }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-subpath
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: conf-vol
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: conf-vol
    configMap:
      name: nginx-custom-conf