apiVersion: v1
kind: ConfigMap
metadata:
  name: app-settings
data:
  settings.ini: | 
    APP_ENV: "production"
    APP_DEBUG: "false"
    APP_VERSION: "1.0.0"

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  password: "Segredo123$"

---

apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app.kubernetes.io/name: webapp
spec:
  containers:
  - name: webapp
    image: nginx
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
    volumeMounts:
      - name: config-volume
        mountPath: /app/config
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

  volumes:
    - name: config-volume
      configMap:
        name: app-settings
