apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage-pod
  labels:
    app.kubernetes.io/name: nginx-storage-pod
spec:
  containers:
  - name: nginx-storage-pod
    image: nginx:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: web-pvc
        mountPath: /usr/share/nginx/html
  volumes:
    - name: web-pvc
      persistentVolumeClaim:
        claimName: web-pvc
