apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    <conteudo do jsonconfig em base64 aqui>

# base64 .docker/config.json
